# used to store sensitive data, such as passwords, tokens, etc.
apiVersion: v1
kind: Secret
metadata:
  # stores credentials to authenticate NDB server
  name: ndb-secret-name
type: Opaque
# stringData contains actual secret data 
stringData:
  username: username-for-ndb-server
  password: password-for-ndb-server
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    CA CERTIFICATE (ca_certificate is optional)
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
# secret needed to manage PostgreSQL Database
metadata:
  name: db-instance-secret-name
type: Opaque
stringData:
  password: password-for-the-database-instance
  ssh_public_key: SSH-PUBLIC-KEY

# These secrets will be used to referenced in custom resources (NDBServer and Database)
# To securely pass credentials when provisioning and accessing the Nutanix Databse Service and PostgreSQL instance
# create secrets in Kubernetes by applying this YAML file using...
# kubectl apply -f secrets.yaml
# ^ securely stores secrets in Kubernetes cluster, relevent applications will be able to access them as needed